// <auto-generated />
using Homate.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Homate.Migrations
{
    [DbContext(typeof(HomateRepositoryContext))]
    [Migration("20230227224918_shopMigration")]
    partial class shopMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Homate.Models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Leziz Ev Yemekleri için iyi bir başlangıç",
                            Name = "Hanife'nin Mekanı"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Çiğköftemiz kötü ama bir sürü sos ve ekstra içerik veriyoruz.",
                            Name = "Komagene Çiğköfte"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Acıkmayın",
                            Name = "Burgerye Ulan"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Beyaz toz harici her türlü sakatat bulunur.",
                            Name = "Koko Faruk"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bildiğin Arby's",
                            Name = "Arby's"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Dünyanın en sıcak pizzası",
                            Name = "Kopernik Pizza"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
